# Site specific settings
title: "Huxnet"
name: "Huxnet"
keywords: "huxnet"
baseurl: "/"
url: "https://huxnet.se"
description: "Website for huxnet"
cover: "/assets/img/cover.svg"
fanpage_id:

# Site general settings
lang: "en"
lang_alternate:
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
